# Generated by Django 2.0.4 on 2018-07-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('description', models.CharField(max_length=250, verbose_name='descrição')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='data de pagto')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='data de vencimento')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='valor')),
                ('payment', models.BooleanField(default=True, help_text='Á vista ou Parcelado.', verbose_name='Á vista?')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago?')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ('-payment_date',),
            },
        ),
        migrations.CreateModel(
            name='TypeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='título')),
            ],
            options={
                'verbose_name': 'Tipo de Despesa',
                'verbose_name_plural': 'Tipos de Despesas',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financial.Expense')),
            ],
            options={
                'verbose_name': 'Recebimento',
                'verbose_name_plural': 'Recebimentos',
                'ordering': ('-payment_date',),
            },
            bases=('financial.expense',),
        ),
        migrations.AddField(
            model_name='expense',
            name='cost_center',
            field=models.ForeignKey(help_text='Recebido/Pago ao (cliente)', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='crm.Company', verbose_name='centro de custo'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paying_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='crm.Employee', verbose_name='fonte pagadora'),
        ),
        migrations.AddField(
            model_name='expense',
            name='type_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='financial.TypeExpense', verbose_name='tipo de despesa'),
        ),
    ]
